[template]
src   = "haproxy.cfg"
dest  = "/etc/haproxy/haproxy.cfg"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/database/credentials/haproxy",
  "/database/port",
  "/database/cluster/mysqlNodes"
]
check_cmd = "/app/bin/check {{ .src }}"
reload_cmd = "/app/bin/reload_haproxy"
